import { createHmac, randomBytes } from "node:crypto";
import { Router } from "express";
import { activeAcademicSessionId, allowRoles, requireAuth, schoolId } from "../auth.js";
import { config } from "../config.js";
import { query, transaction } from "../db.js";
import { ApiError } from "../errors.js";
import type { AuthenticatedRequest } from "../types.js";

export const financeRouter=Router();financeRouter.use(requireAuth);
const staff=allowRoles("SUPER_ADMIN","SCHOOL_OWNER","SCHOOL_ADMIN","TEACHER");
const admin=allowRoles("SUPER_ADMIN","SCHOOL_OWNER","SCHOOL_ADMIN");

const examFields=["academic_session_id","class_id","section_id","section_name","name","exam_type","description","start_date","end_date","result_status","is_active"];
financeRouter.get("/exams/meta",staff,async(req,res)=>{const sid=schoolId(req);const [classes,sections,subjects,teachers]=await Promise.all([query("SELECT id,name FROM school_classes WHERE school_id=$1 AND is_active=true",[sid]),query("SELECT id,name,class_id FROM sections WHERE school_id=$1 AND is_active=true",[sid]),query("SELECT id,name,class_id FROM subjects WHERE school_id=$1 AND is_active=true",[sid]),query("SELECT id,full_name name FROM teachers WHERE school_id=$1 AND is_active=true",[sid])]);res.json({classes:classes.rows,sections:sections.rows,subjects:subjects.rows,teachers:teachers.rows,current_academic_session_id:await activeAcademicSessionId(req)});});
financeRouter.get("/exams",async(req,res)=>{const values:unknown[]=[schoolId(req)];let where="e.school_id=$1";for(const f of ["class_id","section_id","academic_session_id","result_status"]){if(req.query[f]){values.push(req.query[f]);where+=` AND e.${f}=$${values.length}`;}}const r=await query(`SELECT e.*,c.name class_name,s.name section_name,(SELECT COUNT(*)::int FROM exam_subjects es WHERE es.exam_id=e.id) subject_count FROM exams e JOIN school_classes c ON c.id=e.class_id LEFT JOIN sections s ON s.id=e.section_id WHERE ${where} ORDER BY e.start_date DESC,e.id DESC`,values);res.json(r.rows);});
financeRouter.post("/exams",admin,async(req,res)=>{const data:any={...req.body,academic_session_id:req.body.academic_session_id??await activeAcademicSessionId(req)};const cols=examFields.filter(f=>data[f]!==undefined);const r=await query(`INSERT INTO exams(school_id,${cols.join(",")}) VALUES($1,${cols.map((_,i)=>`$${i+2}`).join(",")}) RETURNING *`,[schoolId(req),...cols.map(f=>data[f])]);res.status(201).json(r.rows[0]);});
financeRouter.put("/exams/:id",admin,async(req,res)=>{const cols=examFields.filter(f=>req.body[f]!==undefined);const r=await query(`UPDATE exams SET ${cols.map((f,i)=>`${f}=$${i+1}`).join(",")},updated_at=NOW() WHERE id=$${cols.length+1} AND school_id=$${cols.length+2} RETURNING *`,[...cols.map(f=>req.body[f]),Number(req.params.id),schoolId(req)]);if(!r.rows[0])throw new ApiError(404,"Exam not found");res.json(r.rows[0]);});
financeRouter.delete("/exams/:id",admin,async(req,res)=>{const r=await query("DELETE FROM exams WHERE id=$1 AND school_id=$2 RETURNING id",[Number(req.params.id),schoolId(req)]);if(!r.rowCount)throw new ApiError(404,"Exam not found");res.json({message:"Exam deleted"});});
for(const action of ["publish","unpublish"] as const)financeRouter.post(`/exams/:id/${action}`,admin,async(req,res)=>{const status=action==="publish"?"PUBLISHED":"DRAFT";const r=await query("UPDATE exams SET result_status=$1,published_at=$2,updated_at=NOW() WHERE id=$3 AND school_id=$4 RETURNING *",[status,action==="publish"?new Date():null,Number(req.params.id),schoolId(req)]);if(!r.rows[0])throw new ApiError(404,"Exam not found");res.json(r.rows[0]);});
financeRouter.get("/exams/:id/subjects",async(req,res)=>{const r=await query(`SELECT es.*,s.name subject_name,t.full_name teacher_name FROM exam_subjects es JOIN subjects s ON s.id=es.subject_id LEFT JOIN teachers t ON t.id=es.teacher_id WHERE es.exam_id=$1 AND es.school_id=$2 ORDER BY es.exam_date,s.name`,[Number(req.params.id),schoolId(req)]);res.json(r.rows);});
financeRouter.get("/exams/:id/timetable",async(req,res)=>{const r=await query(`SELECT es.id exam_subject_id,es.exam_id,es.subject_id,s.name subject_name,es.exam_date,es.start_time,es.end_time,es.room,es.timetable_note FROM exam_subjects es JOIN subjects s ON s.id=es.subject_id WHERE es.exam_id=$1 AND es.school_id=$2 ORDER BY es.exam_date,es.start_time`,[Number(req.params.id),schoolId(req)]);res.json(r.rows);});
financeRouter.post("/exams/:id/auto-schedule-timetable",admin,async(req,res)=>{const exam=(await query<any>("SELECT * FROM exams WHERE id=$1 AND school_id=$2",[Number(req.params.id),schoolId(req)])).rows[0];if(!exam)throw new ApiError(404,"Exam not found");const subjects=await query<any>("SELECT * FROM exam_subjects WHERE exam_id=$1 ORDER BY id",[exam.id]);let day=new Date(req.query.start_date as string||exam.start_date||Date.now());for(const [i,s] of subjects.rows.entries()){while([0,6].includes(day.getDay()))day.setDate(day.getDate()+1);await query("UPDATE exam_subjects SET exam_date=$1,start_time=COALESCE(start_time,$2),end_time=COALESCE(end_time,$3) WHERE id=$4",[day.toISOString().slice(0,10),req.query.start_time??"09:00",req.query.end_time??"12:00",s.id]);day.setDate(day.getDate()+1);}res.json((await query("SELECT * FROM exam_subjects WHERE exam_id=$1 ORDER BY exam_date",[exam.id])).rows);});
const examSubjectFields=["subject_id","teacher_id","max_marks","pass_marks","exam_date","start_time","end_time","room","timetable_note","is_active"];
financeRouter.post("/exams/:id/subjects",admin,async(req,res)=>{const cols=examSubjectFields.filter(f=>req.body[f]!==undefined);const r=await query(`INSERT INTO exam_subjects(school_id,exam_id,${cols.join(",")}) VALUES($1,$2,${cols.map((_,i)=>`$${i+3}`).join(",")}) RETURNING *`,[schoolId(req),Number(req.params.id),...cols.map(f=>req.body[f])]);res.status(201).json(r.rows[0]);});
financeRouter.put("/exams/:id/subjects/:subjectId",admin,async(req,res)=>{const cols=examSubjectFields.filter(f=>req.body[f]!==undefined);const r=await query(`UPDATE exam_subjects SET ${cols.map((f,i)=>`${f}=$${i+1}`).join(",")},updated_at=NOW() WHERE id=$${cols.length+1} AND exam_id=$${cols.length+2} AND school_id=$${cols.length+3} RETURNING *`,[...cols.map(f=>req.body[f]),Number(req.params.subjectId),Number(req.params.id),schoolId(req)]);if(!r.rows[0])throw new ApiError(404,"Exam subject not found");res.json(r.rows[0]);});
financeRouter.delete("/exams/:id/subjects/:subjectId",admin,async(req,res)=>{const r=await query("DELETE FROM exam_subjects WHERE id=$1 AND exam_id=$2 AND school_id=$3 RETURNING id",[Number(req.params.subjectId),Number(req.params.id),schoolId(req)]);if(!r.rowCount)throw new ApiError(404,"Exam subject not found");res.json({message:"Exam subject deleted"});});
financeRouter.get("/exams/:id/students",staff,async(req,res)=>{const r=await query(`SELECT s.* FROM students s JOIN exams e ON e.class_id=s.class_id AND (e.section_id IS NULL OR e.section_id=s.section_id) WHERE e.id=$1 AND e.school_id=$2 AND s.is_active=true`,[Number(req.params.id),schoolId(req)]);res.json(r.rows);});
financeRouter.get("/exams/:id/marks",staff,async(req,res)=>{const values:unknown[]=[Number(req.params.id),schoolId(req)];let extra="";if(req.query.exam_subject_id){values.push(Number(req.query.exam_subject_id));extra=` AND es.id=$3`;}const r=await query(`SELECT em.*,es.subject_id,su.name subject_name,concat_ws(' ',st.first_name,st.last_name) student_name,st.admission_no FROM exam_marks em JOIN exam_subjects es ON es.id=em.exam_subject_id JOIN subjects su ON su.id=es.subject_id JOIN students st ON st.id=em.student_id WHERE es.exam_id=$1 AND em.school_id=$2 ${extra} ORDER BY st.first_name`,values);res.json(r.rows);});
financeRouter.post("/exams/:id/marks/bulk",staff,async(req,res)=>{const rows=await transaction(async client=>{const out=[];for(const item of req.body.marks??req.body){const subject=(await client.query<any>("SELECT max_marks,pass_marks FROM exam_subjects WHERE id=$1 AND exam_id=$2 AND school_id=$3",[item.exam_subject_id,Number(req.params.id),schoolId(req)])).rows[0];if(!subject)throw new ApiError(404,"Exam subject not found");const pass=item.is_absent?"ABSENT":Number(item.marks_obtained)>=subject.pass_marks?"PASS":"FAIL";const r=await client.query(`INSERT INTO exam_marks(school_id,exam_subject_id,student_id,marks_obtained,grade,is_absent,pass_status,remarks) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(school_id,exam_subject_id,student_id) DO UPDATE SET marks_obtained=$4,grade=$5,is_absent=$6,pass_status=$7,remarks=$8,updated_at=NOW() RETURNING *`,[schoolId(req),item.exam_subject_id,item.student_id,item.marks_obtained??null,item.grade??null,Boolean(item.is_absent),pass,item.remarks??null]);out.push(r.rows[0]);}return out;});res.json(rows);});
financeRouter.get("/exams/:id/class-result",async(req,res)=>{const r=await query<any>(`SELECT st.id student_id,concat_ws(' ',st.first_name,st.last_name) student_name,COUNT(em.id)::int subjects,COALESCE(SUM(em.marks_obtained),0)::float obtained,COALESCE(SUM(es.max_marks),0)::float maximum,COUNT(*) FILTER(WHERE em.pass_status='FAIL')::int failed FROM exams e JOIN students st ON st.class_id=e.class_id AND(e.section_id IS NULL OR st.section_id=e.section_id) LEFT JOIN exam_subjects es ON es.exam_id=e.id LEFT JOIN exam_marks em ON em.exam_subject_id=es.id AND em.student_id=st.id WHERE e.id=$1 AND e.school_id=$2 GROUP BY st.id ORDER BY obtained DESC`,[Number(req.params.id),schoolId(req)]);res.json({exam_id:Number(req.params.id),students:r.rows});});
financeRouter.get("/exams/:id/subject-result/:subjectId",async(req,res)=>{const r=await query(`SELECT em.*,concat_ws(' ',s.first_name,s.last_name) student_name,s.admission_no FROM exam_marks em JOIN students s ON s.id=em.student_id JOIN exam_subjects es ON es.id=em.exam_subject_id WHERE es.exam_id=$1 AND es.id=$2 AND em.school_id=$3 ORDER BY em.marks_obtained DESC`,[Number(req.params.id),Number(req.params.subjectId),schoolId(req)]);res.json({exam_id:Number(req.params.id),exam_subject_id:Number(req.params.subjectId),students:r.rows});});
async function personalExam(req:import("express").Request,parent:boolean,cards:boolean){const user=(req as AuthenticatedRequest).user;const join=parent?"JOIN parent_guardians g ON g.user_id=$1 JOIN students st ON st.guardian_id=g.id":"JOIN students st ON st.user_id=$1";if(cards)return (await query(`SELECT e.id exam_id,e.name exam_name,st.id student_id,concat_ws(' ',st.first_name,st.last_name) student_name,e.result_status,COALESCE(SUM(em.marks_obtained),0)::float obtained,COALESCE(SUM(es.max_marks),0)::float maximum FROM exams e ${join} AND st.class_id=e.class_id LEFT JOIN exam_subjects es ON es.exam_id=e.id LEFT JOIN exam_marks em ON em.exam_subject_id=es.id AND em.student_id=st.id WHERE e.school_id=$2 AND e.result_status='PUBLISHED' GROUP BY e.id,st.id ORDER BY e.start_date DESC`,[user.id,schoolId(req)])).rows;return(await query(`SELECT es.*,e.name exam_name,su.name subject_name,st.id student_id,concat_ws(' ',st.first_name,st.last_name) student_name FROM exams e ${join} AND st.class_id=e.class_id JOIN exam_subjects es ON es.exam_id=e.id JOIN subjects su ON su.id=es.subject_id WHERE e.school_id=$2 ORDER BY es.exam_date`,[user.id,schoolId(req)])).rows;}
financeRouter.get("/exams/my-timetable",async(req,res)=>res.json(await personalExam(req,false,false)));financeRouter.get("/exams/my-children-timetable",async(req,res)=>res.json(await personalExam(req,true,false)));financeRouter.get("/exams/my-report-cards",async(req,res)=>res.json(await personalExam(req,false,true)));financeRouter.get("/exams/my-children-report-cards",async(req,res)=>res.json(await personalExam(req,true,true)));

financeRouter.get("/fees/meta",async(req,res)=>{const sid=schoolId(req);const [classes,sections,students,categories]=await Promise.all([query("SELECT id,name FROM school_classes WHERE school_id=$1 AND is_active=true",[sid]),query("SELECT id,name,class_id FROM sections WHERE school_id=$1 AND is_active=true",[sid]),query("SELECT id,concat_ws(' ',first_name,last_name) name,class_id,section_id,admission_no FROM students WHERE school_id=$1 AND is_active=true LIMIT 1000",[sid]),query("SELECT id,name FROM fee_categories WHERE school_id=$1 AND is_active=true",[sid])]);res.json({classes:classes.rows,sections:sections.rows,students:students.rows,categories:categories.rows,current_academic_session_id:await activeAcademicSessionId(req)});});
financeRouter.get("/fees/dashboard",admin,async(req,res)=>{const r=await query<any>(`SELECT COALESCE(SUM(amount),0)::float total_assigned,COALESCE(SUM(paid_amount),0)::float total_paid,COALESCE(SUM(balance_amount),0)::float total_pending,COUNT(*) FILTER(WHERE status='OVERDUE')::int overdue_records,(SELECT COALESCE(SUM(amount),0)::float FROM fee_expenses WHERE school_id=$1 AND is_active=true) total_expenses FROM student_fee_records WHERE school_id=$1`,[schoolId(req)]);res.json(r.rows[0]);});
financeRouter.get("/fees/portal",async(req,res)=>{const user=(req as AuthenticatedRequest).user;let records;if(user.role==="PARENT")records=(await query(`SELECT r.*,concat_ws(' ',s.first_name,s.last_name) student_name FROM parent_guardians g JOIN students s ON s.guardian_id=g.id JOIN student_fee_records r ON r.student_id=s.id WHERE g.user_id=$1 ORDER BY r.due_date`,[user.id])).rows;else records=(await query(`SELECT r.*,concat_ws(' ',s.first_name,s.last_name) student_name FROM students s JOIN student_fee_records r ON r.student_id=s.id WHERE s.user_id=$1 ORDER BY r.due_date`,[user.id])).rows;res.json({records,total_due:records.reduce((n:number,r:any)=>n+Number(r.balance_amount),0)});});
const feeResources={categories:{table:"fee_categories",fields:["name","code","description","is_active"]},structures:{table:"fee_structures",fields:["category_id","academic_session_id","name","amount","due_date","description","is_active"]},assignments:{table:"fee_assignments",fields:["fee_structure_id","academic_session_id","class_id","section_id","section_name","student_id","assigned_amount","due_date","note","is_active","generated_at"]},records:{table:"student_fee_records",fields:["student_id","fee_structure_id","fee_assignment_id","academic_session_id","title","amount","discount_amount","fine_amount","paid_amount","balance_amount","due_date","status","note"]},expenses:{table:"fee_expenses",fields:["created_by_user_id","title","category","amount","expense_date","payment_mode","vendor_name","reference_no","note","is_active"]}} as const;
for(const [path,cfg] of Object.entries(feeResources)){
 financeRouter.get(`/fees/${path}`,admin,async(req,res)=>{const values:unknown[]=[schoolId(req)];let where="school_id=$1";for(const f of cfg.fields){if(req.query[f]){values.push(req.query[f]);where+=` AND ${f}=$${values.length}`;}}values.push(Math.min(Number(req.query.limit)||500,1000));res.json((await query(`SELECT * FROM ${cfg.table} WHERE ${where} ORDER BY id DESC LIMIT $${values.length}`,values)).rows);});
 financeRouter.post(`/fees/${path}`,admin,async(req,res)=>{const data:any={...req.body};if(["structures","assignments","records"].includes(path)&&!data.academic_session_id)data.academic_session_id=await activeAcademicSessionId(req);if(path==="records"&&data.balance_amount===undefined)data.balance_amount=Number(data.amount||0)-Number(data.discount_amount||0)+Number(data.fine_amount||0)-Number(data.paid_amount||0);if(path==="expenses")data.created_by_user_id=(req as AuthenticatedRequest).user.id;const cols=cfg.fields.filter(f=>data[f]!==undefined);const r=await query(`INSERT INTO ${cfg.table}(school_id,${cols.join(",")}) VALUES($1,${cols.map((_,i)=>`$${i+2}`).join(",")}) RETURNING *`,[schoolId(req),...cols.map(f=>data[f])]);res.status(201).json(r.rows[0]);});
 financeRouter.put(`/fees/${path}/:id`,admin,async(req,res)=>{const cols=cfg.fields.filter(f=>req.body[f]!==undefined);if(!cols.length)throw new ApiError(422,"No valid fields supplied");const r=await query(`UPDATE ${cfg.table} SET ${cols.map((f,i)=>`${f}=$${i+1}`).join(",")},updated_at=NOW() WHERE id=$${cols.length+1} AND school_id=$${cols.length+2} RETURNING *`,[...cols.map(f=>req.body[f]),Number(req.params.id),schoolId(req)]);if(!r.rows[0])throw new ApiError(404,"Fee record not found");res.json(r.rows[0]);});
 financeRouter.delete(`/fees/${path}/:id`,admin,async(req,res)=>{const r=await query(`DELETE FROM ${cfg.table} WHERE id=$1 AND school_id=$2 RETURNING id`,[Number(req.params.id),schoolId(req)]);if(!r.rowCount)throw new ApiError(404,"Fee record not found");res.json({message:"Deleted successfully"});});
}
financeRouter.post("/fees/assignments/:id/generate-records",admin,async(req,res)=>{const assignment=(await query<any>(`SELECT a.*,s.name structure_name,s.amount structure_amount,s.due_date structure_due_date FROM fee_assignments a JOIN fee_structures s ON s.id=a.fee_structure_id WHERE a.id=$1 AND a.school_id=$2`,[Number(req.params.id),schoolId(req)])).rows[0];if(!assignment)throw new ApiError(404,"Fee assignment not found");const result=await query(`INSERT INTO student_fee_records(school_id,student_id,fee_structure_id,fee_assignment_id,academic_session_id,title,amount,balance_amount,due_date,status)
 SELECT $1,st.id,$2,$3,$4,$5,COALESCE($6,$7),COALESCE($6,$7),COALESCE($8,$9),'PENDING' FROM students st WHERE st.school_id=$1 AND ($10::int IS NULL OR st.id=$10) AND ($11::int IS NULL OR st.class_id=$11) AND ($12::int IS NULL OR st.section_id=$12)
 AND NOT EXISTS(SELECT 1 FROM student_fee_records r WHERE r.student_id=st.id AND r.fee_assignment_id=$3)`,[schoolId(req),assignment.fee_structure_id,assignment.id,assignment.academic_session_id,assignment.structure_name,assignment.assigned_amount,assignment.structure_amount,assignment.due_date,assignment.structure_due_date,assignment.student_id,assignment.class_id,assignment.section_id]);await query("UPDATE fee_assignments SET generated_at=NOW() WHERE id=$1",[assignment.id]);res.json({...assignment,generated_at:new Date(),generated_count:result.rowCount??0});});
financeRouter.get("/fees/payments",admin,async(req,res)=>{const r=await query(`SELECT p.*,concat_ws(' ',s.first_name,s.last_name) student_name,r.title fee_title FROM fee_payments p JOIN students s ON s.id=p.student_id JOIN student_fee_records r ON r.id=p.student_fee_record_id WHERE p.school_id=$1 ORDER BY p.payment_date DESC,p.id DESC LIMIT $2`,[schoolId(req),Math.min(Number(req.query.limit)||500,1000)]);res.json(r.rows);});
financeRouter.post("/fees/payments",admin,async(req,res)=>{const receipt=await transaction(async client=>{const record=(await client.query<any>("SELECT * FROM student_fee_records WHERE id=$1 AND school_id=$2 FOR UPDATE",[req.body.student_fee_record_id,schoolId(req)])).rows[0];if(!record)throw new ApiError(404,"Fee record not found");const amount=Number(req.body.amount);if(amount<=0||amount>Number(record.balance_amount))throw new ApiError(400,"Payment amount is invalid");const receiptNo=req.body.receipt_no??`RCP-${Date.now()}-${randomBytes(2).toString("hex").toUpperCase()}`;const p=await client.query<any>(`INSERT INTO fee_payments(school_id,student_fee_record_id,student_id,collected_by_user_id,receipt_no,amount,payment_date,payment_mode,reference_no,note,razorpay_order_id,razorpay_payment_id,razorpay_signature) VALUES($1,$2,$3,$4,$5,$6,COALESCE($7,CURRENT_DATE),$8,$9,$10,$11,$12,$13) RETURNING *`,[schoolId(req),record.id,record.student_id,(req as AuthenticatedRequest).user.id,receiptNo,amount,req.body.payment_date,req.body.payment_mode??"CASH",req.body.reference_no??null,req.body.note??null,req.body.razorpay_order_id??null,req.body.razorpay_payment_id??null,req.body.razorpay_signature??null]);const paid=Number(record.paid_amount)+amount;const balance=Math.max(0,Number(record.amount)-Number(record.discount_amount)+Number(record.fine_amount)-paid);await client.query("UPDATE student_fee_records SET paid_amount=$1,balance_amount=$2,status=$3,updated_at=NOW() WHERE id=$4",[paid,balance,balance===0?"PAID":"PARTIAL",record.id]);return{payment:p.rows[0],record:{...record,paid_amount:paid,balance_amount:balance,status:balance===0?"PAID":"PARTIAL"}};});res.status(201).json(receipt);});
financeRouter.get("/fees/receipts/:id",async(req,res)=>{const row=(await query(`SELECT p.*,r.title fee_title,r.amount fee_amount,concat_ws(' ',s.first_name,s.last_name) student_name,s.admission_no,sc.name school_name,sc.address school_address FROM fee_payments p JOIN student_fee_records r ON r.id=p.student_fee_record_id JOIN students s ON s.id=p.student_id JOIN schools sc ON sc.id=p.school_id WHERE p.id=$1 AND p.school_id=$2`,[Number(req.params.id),schoolId(req)])).rows[0];if(!row)throw new ApiError(404,"Receipt not found");res.json(row);});
financeRouter.get("/fees/daily-collection",admin,async(req,res)=>{const date=req.query.report_date??new Date().toISOString().slice(0,10);const r=await query<any>(`SELECT COALESCE(SUM(amount),0)::float total,COUNT(*)::int transactions,COALESCE(json_object_agg(payment_mode,mode_total) FILTER(WHERE payment_mode IS NOT NULL),'{}') modes FROM(SELECT payment_mode,SUM(amount)::float mode_total FROM fee_payments WHERE school_id=$1 AND payment_date=$2 GROUP BY payment_mode)x`,[schoolId(req),date]);res.json({report_date:date,...r.rows[0]});});
financeRouter.post("/fees/razorpay/create-order",async(req,res)=>{if(!config.RAZORPAY_KEY_ID||!config.RAZORPAY_KEY_SECRET)throw new ApiError(503,"Razorpay is not configured");const record=(await query<any>("SELECT * FROM student_fee_records WHERE id=$1 AND school_id=$2",[req.body.student_fee_record_id,schoolId(req)])).rows[0];if(!record)throw new ApiError(404,"Fee record not found");const amount=Math.round(Number(req.body.amount??record.balance_amount)*100);const response=await fetch("https://api.razorpay.com/v1/orders",{method:"POST",headers:{Authorization:`Basic ${Buffer.from(`${config.RAZORPAY_KEY_ID}:${config.RAZORPAY_KEY_SECRET}`).toString("base64")}`,"Content-Type":"application/json"},body:JSON.stringify({amount,currency:"INR",receipt:`fee_${record.id}_${Date.now()}`,notes:{record_id:String(record.id)}})});if(!response.ok)throw new ApiError(502,"Payment provider request failed");const order=await response.json();res.json({...order,key_id:config.RAZORPAY_KEY_ID});});
financeRouter.post("/fees/razorpay/verify-payment",async(req,res)=>{if(!config.RAZORPAY_KEY_SECRET)throw new ApiError(503,"Razorpay is not configured");const expected=createHmac("sha256",config.RAZORPAY_KEY_SECRET).update(`${req.body.razorpay_order_id}|${req.body.razorpay_payment_id}`).digest("hex");if(expected!==req.body.razorpay_signature)throw new ApiError(400,"Invalid payment signature");req.body={...req.body,amount:req.body.amount,payment_mode:"RAZORPAY",reference_no:req.body.razorpay_payment_id};const record=(await query<any>("SELECT * FROM student_fee_records WHERE id=$1 AND school_id=$2",[req.body.student_fee_record_id,schoolId(req)])).rows[0];if(!record)throw new ApiError(404,"Fee record not found");const amount=Number(req.body.amount??record.balance_amount);const p=await query<any>(`INSERT INTO fee_payments(school_id,student_fee_record_id,student_id,receipt_no,amount,payment_date,payment_mode,reference_no,razorpay_order_id,razorpay_payment_id,razorpay_signature) VALUES($1,$2,$3,$4,$5,CURRENT_DATE,'RAZORPAY',$6,$7,$6,$8) RETURNING *`,[schoolId(req),record.id,record.student_id,`RCP-${Date.now()}`,amount,req.body.razorpay_payment_id,req.body.razorpay_order_id,req.body.razorpay_signature]);await query("UPDATE student_fee_records SET paid_amount=paid_amount+$1,balance_amount=GREATEST(0,balance_amount-$1),status=CASE WHEN balance_amount-$1<=0 THEN 'PAID' ELSE 'PARTIAL' END WHERE id=$2",[amount,record.id]);res.json(p.rows[0]);});
