import { createHash, randomBytes } from "node:crypto";
import { Router } from "express";
import { allowRoles, requireAuth, schoolId } from "../auth.js";
import { cached } from "../cache.js";
import { config } from "../config.js";
import { query } from "../db.js";
import { ApiError } from "../errors.js";
import type { AuthenticatedRequest } from "../types.js";

export const opsRouter=Router();opsRouter.use(requireAuth);
const staff=allowRoles("SUPER_ADMIN","SCHOOL_OWNER","SCHOOL_ADMIN","TEACHER");
const admin=allowRoles("SUPER_ADMIN","SCHOOL_OWNER","SCHOOL_ADMIN");

opsRouter.get("/dashboard/overview",async(req,res)=>{const user=(req as AuthenticatedRequest).user;const sid=schoolId(req);const data=await cached(`school:${sid}:dashboard:${user.role}:${user.id}`,30,async()=>{const school=(await query<any>("SELECT id,name,institution_type type,school_code FROM schools WHERE id=$1",[sid])).rows[0];const session=(await query<any>("SELECT * FROM academic_sessions WHERE school_id=$1 AND is_active=true ORDER BY id DESC LIMIT 1",[sid])).rows[0]??null;const counts=(await query<any>(`SELECT (SELECT COUNT(*)::int FROM students WHERE school_id=$1 AND is_active=true) students,(SELECT COUNT(*)::int FROM teachers WHERE school_id=$1 AND is_active=true) teachers,(SELECT COUNT(*)::int FROM school_classes WHERE school_id=$1 AND is_active=true) classes,(SELECT COUNT(*)::int FROM homework_assignments WHERE school_id=$1 AND is_active=true) homework,(SELECT COUNT(*)::int FROM exams WHERE school_id=$1 AND is_active=true) exams,(SELECT COALESCE(SUM(balance_amount),0)::float FROM student_fee_records WHERE school_id=$1) pending_fees,(SELECT COUNT(*)::int FROM notices WHERE school_id=$1 AND status='PUBLISHED') notices`,[sid])).rows[0];const cards=Object.entries(counts).slice(0,6).map(([key,value])=>({key,label:key.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase()),value:value as number,tone:key==="pending_fees"?"warning":"info"}));return{school,user:{id:user.id,full_name:user.full_name,role:user.role,login_id:user.login_id,must_change_password:user.must_change_password},role_dashboard:user.role==="TEACHER"?"teacher":user.role==="STUDENT"?"student":user.role==="PARENT"?"parent":"admin",title:`${user.role.replaceAll("_"," ")} Dashboard`,description:"Live school operations and activity summary.",cards,counts,current_academic_session:session,recent_activities:[],charts:[{title:"School Overview",type:"bar",items:[{label:"Students",value:counts.students},{label:"Teachers",value:counts.teachers},{label:"Classes",value:counts.classes},{label:"Exams",value:counts.exams}]}],quick_search_enabled:true};});res.json(data);});
opsRouter.get("/dashboard/quick-search",async(req,res)=>{const q=String(req.query.q??"").trim();if(q.length<2)return res.json({results:[]});const pattern=`%${q}%`;const sid=schoolId(req);const result=await query<any>(`SELECT * FROM(SELECT 'student' kind,concat_ws(' ',first_name,last_name) title,concat('Admission: ',admission_no) subtitle,'/students' href FROM students WHERE school_id=$1 AND(concat_ws(' ',first_name,last_name) ILIKE $2 OR admission_no ILIKE $2) UNION ALL SELECT 'teacher',full_name,concat('Employee: ',employee_id),'/teachers' FROM teachers WHERE school_id=$1 AND(full_name ILIKE $2 OR employee_id ILIKE $2) UNION ALL SELECT 'course',title,COALESCE(description,''),'/courses' FROM courses WHERE school_id=$1 AND title ILIKE $2 UNION ALL SELECT 'book',title,author,'/library' FROM library_books WHERE school_id=$1 AND(title ILIKE $2 OR author ILIKE $2))x LIMIT 20`,[sid,pattern]);res.json({results:result.rows});});

opsRouter.get("/reports/overview",admin,async(req,res)=>{const r=await query<any>(`SELECT (SELECT COUNT(*)::int FROM students WHERE school_id=$1) total_students,(SELECT COUNT(*)::int FROM students WHERE school_id=$1 AND is_active=true) active_students,(SELECT COUNT(*)::int FROM teachers WHERE school_id=$1) total_teachers,(SELECT COUNT(*)::int FROM teachers WHERE school_id=$1 AND is_active=true) active_teachers,(SELECT COUNT(*)::int FROM school_classes WHERE school_id=$1) total_classes,(SELECT COUNT(*)::int FROM exams WHERE school_id=$1) total_exams,(SELECT COUNT(*)::int FROM exams WHERE school_id=$1 AND result_status='PUBLISHED') published_exams,(SELECT COUNT(*)::int FROM homework_assignments WHERE school_id=$1) total_homework,(SELECT COALESCE(ROUND(100.0*COUNT(*) FILTER(WHERE status='PRESENT')/NULLIF(COUNT(*),0),2),0)::float FROM student_attendance WHERE school_id=$1) avg_attendance_pct,(SELECT COUNT(*)::int FROM library_books WHERE school_id=$1) library_books,(SELECT COUNT(*)::int FROM library_issues WHERE school_id=$1 AND status='ISSUED') library_issued,(SELECT COUNT(*)::int FROM library_issues WHERE school_id=$1 AND status='ISSUED' AND due_date<CURRENT_DATE) overdue_books`,[schoolId(req)]);res.json({...r.rows[0],low_attendance_students:0});});
opsRouter.get("/reports/students",admin,async(req,res)=>{const values:unknown[]=[schoolId(req)];let where="s.school_id=$1";if(req.query.class_id){values.push(req.query.class_id);where+=` AND s.class_id=$${values.length}`;}if(req.query.section_id){values.push(req.query.section_id);where+=` AND s.section_id=$${values.length}`;}const rows=await query<any>(`SELECT s.id student_id,s.admission_no,s.roll_number,concat_ws(' ',s.first_name,s.last_name) full_name,s.photo_url,s.gender,c.name class_name,se.name section_name,g.full_name guardian_name,g.phone guardian_phone,s.admission_date,s.status FROM students s LEFT JOIN school_classes c ON c.id=s.class_id LEFT JOIN sections se ON se.id=s.section_id LEFT JOIN parent_guardians g ON g.id=s.guardian_id WHERE ${where} ORDER BY full_name`,values);const breakdown=await query<any>(`SELECT c.name class,COUNT(*)::int count FROM students s JOIN school_classes c ON c.id=s.class_id WHERE s.school_id=$1 GROUP BY c.name ORDER BY c.name`,[schoolId(req)]);res.json({total_students:rows.rowCount??0,active_students:rows.rows.filter((x:any)=>x.status==="ACTIVE").length,class_breakdown:breakdown.rows,rows:rows.rows});});
opsRouter.get("/reports/attendance",admin,async(req,res)=>{const values:unknown[]=[schoolId(req)];let where="s.school_id=$1";const filters: Array<[string,string]>=[["class_id","s.class_id"],["section_id","s.section_id"],["session_id","a.session_id"]];for(const [p,c] of filters)if(req.query[p]){values.push(req.query[p]);where+=` AND ${c}=$${values.length}`;}if(req.query.date_from){values.push(req.query.date_from);where+=` AND a.date>=$${values.length}`;}if(req.query.date_to){values.push(req.query.date_to);where+=` AND a.date<=$${values.length}`;}const rows=await query<any>(`SELECT s.id student_id,concat_ws(' ',s.first_name,s.last_name) student_name,s.admission_no,s.roll_number,c.name class_name,se.name section_name,COUNT(a.id)::int total_days,COUNT(*) FILTER(WHERE a.status='PRESENT')::int present,COUNT(*) FILTER(WHERE a.status='ABSENT')::int absent,COUNT(*) FILTER(WHERE a.status='LEAVE')::int leave,COUNT(*) FILTER(WHERE a.status='HALF_DAY')::int half_day,ROUND(CASE WHEN COUNT(a.id)=0 THEN 0 ELSE 100.0*COUNT(*) FILTER(WHERE a.status='PRESENT')/COUNT(a.id) END,2)::float percentage FROM students s LEFT JOIN school_classes c ON c.id=s.class_id LEFT JOIN sections se ON se.id=s.section_id LEFT JOIN student_attendance a ON a.student_id=s.id WHERE ${where} GROUP BY s.id,c.name,se.name ORDER BY student_name`,values);const mapped=rows.rows.map((x:any)=>({...x,low_attendance:x.percentage<75}));const avg=mapped.length?mapped.reduce((n:number,x:any)=>n+x.percentage,0)/mapped.length:0;res.json({session_name:"Selected session",total_students:mapped.length,avg_percentage:Math.round(avg*100)/100,low_attendance_count:mapped.filter((x:any)=>x.low_attendance).length,rows:mapped});});
opsRouter.get("/reports/teachers",admin,async(req,res)=>{const rows=await query<any>(`SELECT t.id teacher_id,t.employee_id,t.full_name,t.photo_url,d.name department_name,t.email,t.phone,t.qualification,t.joining_date,t.status,(SELECT COUNT(*)::int FROM teacher_subjects ts WHERE ts.teacher_id=t.id) subjects_assigned,(SELECT COUNT(*)::int FROM class_teacher_assignments cta WHERE cta.teacher_id=t.id) classes_assigned FROM teachers t LEFT JOIN departments d ON d.id=t.department_id WHERE t.school_id=$1 ORDER BY t.full_name`,[schoolId(req)]);const breakdown=await query<any>(`SELECT COALESCE(d.name,'Unassigned') department,COUNT(*)::int count FROM teachers t LEFT JOIN departments d ON d.id=t.department_id WHERE t.school_id=$1 GROUP BY d.name ORDER BY department`,[schoolId(req)]);res.json({total_teachers:rows.rowCount??0,active_teachers:rows.rows.filter((x:any)=>x.status==="ACTIVE").length,department_breakdown:breakdown.rows,rows:rows.rows});});
opsRouter.get("/reports/homework",admin,async(req,res)=>{const rows=await query<any>(`SELECT h.id assignment_id,h.title,su.name subject_name,c.name class_name,se.name section_name,h.due_date,t.full_name teacher_name,COUNT(st.id)::int total_students,COUNT(hs.id) FILTER(WHERE hs.status='SUBMITTED')::int submitted,COUNT(hs.id) FILTER(WHERE hs.status='CHECKED')::int checked,(COUNT(st.id)-COUNT(hs.id))::int pending,ROUND(CASE WHEN COUNT(st.id)=0 THEN 0 ELSE 100.0*COUNT(hs.id)/COUNT(st.id) END,2)::float submission_rate FROM homework_assignments h JOIN school_classes c ON c.id=h.class_id LEFT JOIN sections se ON se.id=h.section_id LEFT JOIN subjects su ON su.id=h.subject_id LEFT JOIN teachers t ON t.id=h.teacher_id LEFT JOIN students st ON st.class_id=h.class_id AND(h.section_id IS NULL OR st.section_id=h.section_id) LEFT JOIN homework_submissions hs ON hs.homework_id=h.id AND hs.student_id=st.id WHERE h.school_id=$1 GROUP BY h.id,su.name,c.name,se.name,t.full_name ORDER BY h.due_date DESC`,[schoolId(req)]);res.json({rows:rows.rows});});
opsRouter.get("/reports/fees",admin,async(req,res)=>{const r=await query<any>(`SELECT COALESCE(SUM(amount),0)::float assessed,COALESCE(SUM(paid_amount),0)::float collected,COALESCE(SUM(balance_amount),0)::float outstanding,COUNT(*) FILTER(WHERE status='OVERDUE')::int overdue FROM student_fee_records WHERE school_id=$1`,[schoolId(req)]);res.json(r.rows[0]);});

opsRouter.get("/meetings/stats",staff,async(req,res)=>{const r=await query<any>(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE status='live')::int live,COUNT(*) FILTER(WHERE status='scheduled')::int scheduled,COUNT(*) FILTER(WHERE status='ended')::int ended FROM meetings WHERE school_id=$1`,[schoolId(req)]);res.json(r.rows[0]);});
opsRouter.get("/meetings/active/class/:classId",async(req,res)=>{const row=(await query("SELECT * FROM meetings WHERE school_id=$1 AND class_id=$2 AND status='live' ORDER BY started_at DESC LIMIT 1",[schoolId(req),Number(req.params.classId)])).rows[0];res.json(row??null);});
opsRouter.get("/meetings/",async(req,res)=>{const user=(req as AuthenticatedRequest).user;const values:unknown[]=[schoolId(req)];let where="school_id=$1";if(user.role==="TEACHER"){const t=(await query<any>("SELECT id FROM teachers WHERE user_id=$1",[user.id])).rows[0];values.push(t?.id??-1);where+=` AND (teacher_id=$2 OR meeting_type='admin_teachers')`;}res.json((await query(`SELECT * FROM meetings WHERE ${where} ORDER BY COALESCE(scheduled_at,created_at) DESC LIMIT 200`,values)).rows);});
opsRouter.get("/meetings/teacher/my-classes",staff,async(req,res)=>{const user=(req as AuthenticatedRequest).user;if(["SUPER_ADMIN","SCHOOL_OWNER","SCHOOL_ADMIN"].includes(user.role))return res.json({classes:(await query("SELECT id,name FROM school_classes WHERE school_id=$1 AND is_active=true",[schoolId(req)])).rows});const r=await query("SELECT DISTINCT c.id,c.name FROM teachers t JOIN class_teacher_assignments x ON x.teacher_id=t.id JOIN school_classes c ON c.id=x.class_id WHERE t.user_id=$1",[user.id]);res.json({classes:r.rows});});
opsRouter.get("/meetings/class/:classId/students",staff,async(req,res)=>res.json((await query("SELECT id,concat_ws(' ',first_name,last_name) full_name,admission_no FROM students WHERE school_id=$1 AND class_id=$2 AND is_active=true",[schoolId(req),Number(req.params.classId)])).rows));
async function createMeeting(req:import("express").Request,live:boolean,type:"teacher_class"|"admin_teachers"){const bbbId=`erp-${schoolId(req)}-${Date.now()}-${randomBytes(3).toString("hex")}`;const attendee=randomBytes(8).toString("hex"),moderator=randomBytes(8).toString("hex");const r=await query<any>(`INSERT INTO meetings(school_id,bbb_meeting_id,attendee_password,moderator_password,title,meeting_type,status,created_by_user_id,class_id,section_id,section_name,teacher_id,record,scheduled_at,started_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING *`,[schoolId(req),bbbId,attendee,moderator,req.body.title,type,live?"live":"scheduled",(req as AuthenticatedRequest).user.id,req.body.class_id??null,req.body.section_id??null,req.body.section_name??null,req.body.teacher_id??null,req.body.record!==false,req.body.scheduled_at??null,live?new Date():null]);return r.rows[0];}
opsRouter.post("/meetings/teacher/class",staff,async(req,res)=>res.status(201).json(await createMeeting(req,true,"teacher_class")));opsRouter.post("/meetings/admin/teachers",admin,async(req,res)=>res.status(201).json(await createMeeting(req,true,"admin_teachers")));opsRouter.post("/meetings/teacher/class/schedule",staff,async(req,res)=>res.status(201).json(await createMeeting(req,false,"teacher_class")));opsRouter.post("/meetings/admin/teachers/schedule",admin,async(req,res)=>res.status(201).json(await createMeeting(req,false,"admin_teachers")));
opsRouter.post("/meetings/:id/start",staff,async(req,res)=>{const r=await query("UPDATE meetings SET status='live',started_at=NOW() WHERE id=$1 AND school_id=$2 RETURNING *",[Number(req.params.id),schoolId(req)]);if(!r.rows[0])throw new ApiError(404,"Meeting not found");res.json(r.rows[0]);});
opsRouter.delete("/meetings/:id/cancel",staff,async(req,res)=>{const r=await query("DELETE FROM meetings WHERE id=$1 AND school_id=$2 AND status='scheduled' RETURNING id",[Number(req.params.id),schoolId(req)]);if(!r.rowCount)throw new ApiError(404,"Scheduled meeting not found");res.json({message:"Meeting cancelled"});});
opsRouter.get("/meetings/:id/join",async(req,res)=>{const user=(req as AuthenticatedRequest).user;const m=(await query<any>("SELECT * FROM meetings WHERE id=$1 AND school_id=$2",[Number(req.params.id),schoolId(req)])).rows[0];if(!m)throw new ApiError(404,"Meeting not found");if(!config.BBB_URL||!config.BBB_SECRET)return res.json({join_url:null,meeting:m,message:"Configure BBB_URL and BBB_SECRET to enable joining"});const password=["SUPER_ADMIN","SCHOOL_OWNER","SCHOOL_ADMIN","TEACHER"].includes(user.role)?m.moderator_password:m.attendee_password;const queryString=new URLSearchParams({fullName:user.full_name,meetingID:m.bbb_meeting_id,password,redirect:"true"}).toString();const checksum=createHash("sha1").update(`join${queryString}${config.BBB_SECRET}`).digest("hex");res.json({join_url:`${config.BBB_URL.replace(/\/$/,"")}/join?${queryString}&checksum=${checksum}`});});
opsRouter.post("/meetings/:id/end",staff,async(req,res)=>{const r=await query("UPDATE meetings SET status='ended',ended_at=NOW() WHERE id=$1 AND school_id=$2 RETURNING *",[Number(req.params.id),schoolId(req)]);if(!r.rows[0])throw new ApiError(404,"Meeting not found");res.json(r.rows[0]);});
